AllCops:
  Exclude:
    - 'spec/tmp/**/*.rb'

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'uploadcare-rails.gemspec'

Metrics/ClassLength:
  Exclude:
    - 'lib/uploadcare/rails/transformations/image_transformations.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'uploadcare-rails.gemspec'
    - 'lib/uploadcare/rails/active_record/mount_uploadcare_file.rb'

Naming/FileName:
  Exclude:
    - 'lib/uploadcare-rails.rb'

Style/HashTransformKeys:
  Exclude:
    - 'lib/uploadcare/rails/action_view/uploadcare_uploader_tags.rb'
    - 'lib/uploadcare/rails/transformations/image_transformations.rb'
