Gemspec/RequiredRubyVersion:
  Exclude:
    - 'uploadcare-rails.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/uploadcare/rails/**/*.rb'
    - 'spec/helpers/**/*.rb'
    - 'uploadcare-rails.gemspec'

Naming/FileName:
  Exclude:
    - 'lib/uploadcare-rails.rb'

Style/HashTransformKeys:
  Exclude:
    - 'lib/uploadcare/rails/action_view/uploadcare_uploader_tags.rb'
