name: Publish Gem

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Release Gem
        if: contains(github.ref, 'refs/tags/v')
        uses: discourse/publish-rubygems-action@main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake release
          GIT_EMAIL: hello@uploadcare.com
          GIT_NAME: Uploadcare Developers
