name: Test
on: [push, pull_request]
jobs:
  test:
    needs: code-analysis
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          - gemfile: Gemfile
            ruby: "3.3"
            experimental: false
          - gemfile: Gemfile
            ruby: "3.4"
            experimental: false
          - gemfile: gemfiles/Gemfile-rails-8-0
            ruby: "3.4"
            experimental: false
          - gemfile: gemfiles/Gemfile-rails-7-2
            ruby: "3.4"
            experimental: false
          - gemfile: gemfiles/Gemfile-rails-7-1
            ruby: "3.3"
            experimental: false
          - gemfile: gemfiles/Gemfile-rails-7-0
            ruby: "3.3"
            experimental: false
          - gemfile: gemfiles/Gemfile-rails-main
            ruby: "3.4"
            experimental: true
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      UPLOADCARE_PUBLIC_KEY: demopublickey
      UPLOADCARE_SECRET_KEY: demoprivatekey
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs bundle install and caches installed gems automatically
      - run: bundle exec rake

  code-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - "3.4"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Check code
      run: bundle exec rubocop
